# agent/llm/providers/base.py

"""
Base Provider Interface - Defines the contract for all LLM backends.

All concrete provider implementations (e.g., OpenAI, Anthropic, Mock) must
inherit from this class and implement its abstract methods.
"""

from typing import List, Dict
from abc import ABC, abstractmethod

class BaseProvider(ABC):
    """
    Abstract base class for all LLM providers.
    """

    @abstractmethod
    def generate(self, messages: List[Dict[str, str]]) -> str:
        """
        Generates a text completion for the provided message context.

        Args:
            messages: A list of dictionaries representing the chat history
                (e.g., [{"role": "user", "content": "..."}]).

        Returns:
            str: The text content generated by the provider.
        """
        pass
